### ISSUE TITLE
RangeError [ERR_INVALID_OPT_VALUE] ...

### ISSUE THREAD

**Issue by totlsota** [aksakalli/gtop#120]
#### Environment

- OS: Ubuntu 21.10 
- Node version: v12.22.5
- gtop version: 1.1.2 

#### Description

Newly installed, run and getting this error. 

RangeError [ERR_INVALID_OPT_VALUE]: The value "-36" is invalid for option "size"
    at Function.alloc (buffer.js:370:3)
    at new Buffer (buffer.js:284:19)   
    at new Canvas (/usr/local/lib/node_modules/gtop/node_modules/drawille-blessed-contrib/index.js:17:18)           
    at new Context (/usr/local/lib/node_modules/gtop/node_modules/drawille-canvas-blessed-contrib/index.js:11:18)   
    at module.exports.Canvas.getContext (/usr/local/lib/node_modules/gtop/node_modules/drawille-canvas-blessed-contrib/index.js:274:24)                                                                                                   
    at Donut.<anonymous> (/usr/local/lib/node_modules/gtop/node_modules/blessed-contrib/lib/widget/canvas.js:23:29) 
    at Donut.EventEmitter._emit (/usr/local/lib/node_modules/gtop/node_modules/blessed/lib/events.js:98:20)       
    at Donut.EventEmitter.emit (/usr/local/lib/node_modules/gtop/node_modules/blessed/lib/events.js:117:12)       
    at emit (/usr/local/lib/node_modules/gtop/node_modules/blessed/lib/widgets/node.js:109:15)                    
    at Screen.Node.insert (/usr/local/lib/node_modules/gtop/node_modules/blessed/lib/widgets/node.js:111:5)

**Comment by aksakalli** [comment]
Hi, where do you run it? Is it in an IDE to debug? might be related to a small terminal size.

**Comment by totlsota** [comment]
You had it right; I had it in too small a terminal size. Sorted as long as running on big enough terminal. Tx.
