### ISSUE TITLE
RangeError in webstorm terminal

### ISSUE THREAD

**Issue by ganyusheng520** [aksakalli/gtop#28]
#### Environment

- OS: macOS 10.12.6
- Node version: v8.3.0
- gtop version: v5.3.0

#### Description
when I run 'gtop' in webstorm terminal:

RangeError: "size" argument must not be negative
    at Function.Buffer.alloc (buffer.js:229:3)
    at new Buffer (buffer.js:152:19)
    at new Canvas (/usr/local/lib/node_modules/gtop/node_modules/drawille-blessed-contrib/index.js:17:18)
    at new Context (/usr/local/lib/node_modules/gtop/node_modules/drawille-canvas-blessed-contrib/index.js:11:18)
    at module.exports.Canvas.getContext (/usr/local/lib/node_modules/gtop/node_modules/drawille-canvas-blessed-contrib/index.js:274:24)
    at Donut.<anonymous> (/usr/local/lib/node_modules/gtop/node_modules/blessed-contrib/lib/widget/canvas.js:22:29)
    at Donut.EventEmitter._emit (/usr/local/lib/node_modules/gtop/node_modules/blessed/lib/events.js:98:20)
    at Donut.EventEmitter.emit (/usr/local/lib/node_modules/gtop/node_modules/blessed/lib/events.js:117:12)
    at emit (/usr/local/lib/node_modules/gtop/node_modules/blessed/lib/widgets/node.js:109:15)
    at Screen.Node.insert (/usr/local/lib/node_modules/gtop/node_modules/blessed/lib/widgets/node.js:111:5)

But It's OK in the system terminal.

**Comment by aksakalli** [comment]
The built in terminal in Webstorm might not have the required character size. Alternatively, you can try remote debug by running the app as:

```
node --debug bin/gtop
```

in the system terminal.
