### ISSUE TITLE
cpu.js SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by firetaker** [aksakalli/gtop#5]
below is my work env: 
~# nodejs -v
v0.10.25

~# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.3 LTS
Release:	14.04
Codename:	trusty

~# npm install gtip -g

when run gtop cli I got this error:
~#gtop 
/usr/local/lib/node_modules/gtop/lib/monitor/cpu.js:8
  si.currentLoad(data => {
                       ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/gtop/lib/monitor/index.js:2:8)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

**Comment by loatheb** [comment]
@firetaker
the reason I think is you have a very low node version that doesn't support the arrow function. 
to solve this, you can use [nvm](https://github.com/creationix/nvm) to install multiple node version in your local, or just upgrade to a higher version.

**Comment by aksakalli** [comment]
Hi, 

That's right, you need at least `v4`. #8
