### ISSUE TITLE
can't run on centos 7

### ISSUE THREAD

**Issue by cipixul** [aksakalli/gtop#7]
I installed npm with yum -y install npm
then I installed gtop with npm install gtop -g
and when I ran gtop I have this error:

/usr/lib/node_modules/gtop/lib/monitor/cpu.js:8
  si.currentLoad(data => {
                       ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/lib/node_modules/gtop/lib/monitor/index.js:2:8)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

Please tell me what other info do you need to have a better idea of the bug :)

**Comment by aksakalli** [comment]
hi,

You are most likely using a very old nodejs version. Please use at least `node>=v4`. #8, #5
