### ISSUE TITLE
Error: Width must be multiple of 2!

### ISSUE THREAD

**Issue by HZooly** [aksakalli/gtop#70]
#### Environment

- OS: Windows 10 64Bits
- Node version: 7.5.0
- gtop version: 0.1.5

#### Description

I just installed **gtop** with `npm`, and tried to run it.
Unfortunately, I got the following error:

```
Error: Width must be multiple of 2!
    at new Canvas (C:\Users\USER\AppData\Roaming\npm\node_modules\gtop\node_modules\drawille-blessed-contrib\index.js:10:11)
    at new Context (C:\Users\USER\AppData\Roaming\npm\node_modules\gtop\node_modules\drawille-canvas-blessed-contrib\index.js:11:18)
    at module.exports.Canvas.getContext (C:\Users\USER\AppData\Roaming\npm\node_modules\gtop\node_modules\drawille-canvas-blessed-contrib\index.js:274:24)
    at Donut.<anonymous> (C:\Users\USER\AppData\Roaming\npm\node_modules\gtop\node_modules\blessed-contrib\lib\widget\canvas.js:22:29)
    at Donut.EventEmitter._emit (C:\Users\USER\AppData\Roaming\npm\node_modules\gtop\node_modules\blessed\lib\events.js:98:20)
    at Donut.EventEmitter.emit (C:\Users\USER\AppData\Roaming\npm\node_modules\gtop\node_modules\blessed\lib\events.js:117:12)
    at emit (C:\Users\USER\AppData\Roaming\npm\node_modules\gtop\node_modules\blessed\lib\widgets\node.js:109:15)
    at Screen.Node.insert (C:\Users\USER\AppData\Roaming\npm\node_modules\gtop\node_modules\blessed\lib\widgets\node.js:111:5)
    at Screen.Node.append (C:\Users\USER\AppData\Roaming\npm\node_modules\gtop\node_modules\blessed\lib\widgets\node.js:123:8)
    at Grid.set (C:\Users\USER\AppData\Roaming\npm\node_modules\gtop\node_modules\blessed-contrib\lib\layout\grid.js:35:24)

```

I'm trying to run **gtop**  in Git Bash terminal.

**Note** : Working perfectly with Powershell.

**Comment by aksakalli** [comment]
duplicate #76
