### ISSUE TITLE
get SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by diggde** [aksakalli/gtop#81]
#### Environment

- OS: turnkey lamp 14
- Node version: v0.10.29
- gtop version: 1.0.0

apt info:
nodejs-legacy is already the newest version.
npm is already the newest version.

#### Description

Hi,

i get a warning during installation:
`npm WARN marked-terminal@1.7.0 requires a peer of marked@^0.3.3 but none was installed.`

and i get a syntax error after installing gtop:

/usr/lib/node_modules/gtop/lib/monitor/cpu.js:8
  si.currentLoad(data => {
                                  ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/lib/node_modules/gtop/lib/monitor/index.js:2:8)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

Can anybody help?

**Comment by aksakalli** [comment]
your node version is not compatible:

* Node.js >= v4
